package com.bootcampjava.electricityservice.soapservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-17T13:18:33.454-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://serviceplan.soapservice.webservices.services.electricityservice.cmsenergy.com/", name = "PowerPlanService")
@XmlSeeAlso({ObjectFactory.class})
public interface PowerPlanService {

    @WebMethod
    @RequestWrapper(localName = "getServicePlans", targetNamespace = "http://serviceplan.soapservice.webservices.services.electricityservice.cmsenergy.com/", className = "com.bootcampjava.electricityservice.soapservice.GetServicePlans")
    @ResponseWrapper(localName = "getServicePlansResponse", targetNamespace = "http://serviceplan.soapservice.webservices.services.electricityservice.cmsenergy.com/", className = "com.bootcampjava.electricityservice.soapservice.GetServicePlansResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.bootcampjava.electricityservice.soapservice.ServicePlan> getServicePlans();
}
