package com.xcelenergy.electricityservice.soapservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-17T23:19:42.653-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "servicePlan", 
                  wsdlLocation = "file:/C:/Users/Bootcamp%20User%20000/git/customerUtility/electricityserviceconsumer/src/main/resources/customerService.wsdl",
                  targetNamespace = "http://serviceplan.soapservice.webservices.services.electricityservice.cmsenergy.com/") 
public class ServicePlan_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://serviceplan.soapservice.webservices.services.electricityservice.cmsenergy.com/", "servicePlan");
    public final static QName PowerPlanServiceImplPort = new QName("http://serviceplan.soapservice.webservices.services.electricityservice.cmsenergy.com/", "PowerPlanServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Bootcamp%20User%20000/git/customerUtility/electricityserviceconsumer/src/main/resources/customerService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicePlan_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Bootcamp%20User%20000/git/customerUtility/electricityserviceconsumer/src/main/resources/customerService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicePlan_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicePlan_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicePlan_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ServicePlan_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicePlan_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicePlan_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PowerPlanService
     */
    @WebEndpoint(name = "PowerPlanServiceImplPort")
    public PowerPlanService getPowerPlanServiceImplPort() {
        return super.getPort(PowerPlanServiceImplPort, PowerPlanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PowerPlanService
     */
    @WebEndpoint(name = "PowerPlanServiceImplPort")
    public PowerPlanService getPowerPlanServiceImplPort(WebServiceFeature... features) {
        return super.getPort(PowerPlanServiceImplPort, PowerPlanService.class, features);
    }

}
